package com.example.model

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

enum class ThemeStyle(val displayName: String, val iconEmoji: String, val subtitle: String) {
    SEMI_TRANSPARENT("Semi-Transparent", "🫧", "Translucent glass with see-through gradient"),
    TACTILE_3D("3D Buttons", "🔘", "Sculpted tactile keys with mechanical spring press"),
    NEUMORPHISM_LIGHT("Neumorphism Light", "☁️", "Soft UI extruded depth with dual lighting"),
    NEUMORPHISM_DARK("Neumorphism Dark", "🌑", "Dark Soft UI with subtle ambient glow"),
    GLASSMORPHISM("Glassmorphism", "🧊", "Frosted glass sheen with refraction border"),
    SKEUOMORPHISM("Skeuomorphism", "🕹️", "Realistic glossy 3D keycaps & tactile depth"),
    CLAYMORPHISM("Claymorphism", "🎨", "Puffy marshmallow 3D clay with soft floating volume"),
    FLAT_DESIGN("Flat Design", "📐", "Clean minimalist flat surface with zero shadows"),
    FLAT_2_0("Flat 2.0", "✨", "Modern semi-flat with subtle layered micro-depth"),
    NEOBRUTALISM("Neobrutalism", "⚡", "High-contrast thick black borders & hard offset shadow"),
    MINIMALISM("Minimalism", "⚪", "Ultra-light typography and subtle outline"),
    MATERIAL_YOU("Material You", "📱", "Adaptive Android dynamic styling"),
    STANDARD("Standard", "⌨️", "Classic standard keyboard")
}

data class KeyboardTheme(
    val id: String,
    val name: String,
    val isDark: Boolean,
    val primaryColor: Color,
    val backgroundColor: Color,
    val surfaceColor: Color,
    val keyColor: Color,
    val keySpecialColor: Color,
    val keyPressedColor: Color,
    val textColor: Color,
    val textSecondaryColor: Color,
    val accentColor: Color,
    val keyBorderColor: Color,
    val backgroundGradient: List<Color>? = null,
    val keyAlpha: Float = 1.0f,
    val backdropType: String = "solid",
    val themeStyle: ThemeStyle = ThemeStyle.STANDARD,
    val keyCornerRadius: Float = 8f,
    val keyElevation: Float = 1.5f,
    val category: String = "Popular",
    val isPro: Boolean = false
) {
    companion object {
        val MIDNIGHT = KeyboardTheme(
            id = "midnight",
            name = "Immersive Dark",
            isDark = true,
            primaryColor = Color(0xFF6366F1),
            backgroundColor = Color(0xFF16161D),
            surfaceColor = Color(0xFF1C1C24),
            keyColor = Color(0xFF2C2C38),
            keySpecialColor = Color(0xFF3D3D4D),
            keyPressedColor = Color(0xFF4B4B5E),
            textColor = Color(0xFFF1F5F9),
            textSecondaryColor = Color(0xFF94A3B8),
            accentColor = Color(0xFF818CF8),
            keyBorderColor = Color(0x1AFFFFFF),
            backdropType = "solid"
        )

        val COSMIC = KeyboardTheme(
            id = "cosmic",
            name = "Cosmic Nebula",
            isDark = true,
            primaryColor = Color(0xFFA855F7),
            backgroundColor = Color(0xFF0D0B1E),
            surfaceColor = Color(0xFF181533),
            keyColor = Color(0x33382BF0),
            keySpecialColor = Color(0x55581C87),
            keyPressedColor = Color(0x777C3AED),
            textColor = Color(0xFFFAF5FF),
            textSecondaryColor = Color(0xFFD8B4FE),
            accentColor = Color(0xFFC084FC),
            keyBorderColor = Color(0x44A855F7),
            backgroundGradient = listOf(Color(0xFF0F0C29), Color(0xFF302B63), Color(0xFF24243E)),
            keyAlpha = 0.85f,
            backdropType = "cosmic",
            isPro = true
        )

        val SUNSET = KeyboardTheme(
            id = "sunset",
            name = "Sunset Horizon",
            isDark = true,
            primaryColor = Color(0xFFF43F5E),
            backgroundColor = Color(0xFF1C0A1E),
            surfaceColor = Color(0xFF2E1035),
            keyColor = Color(0x38FF4D6D),
            keySpecialColor = Color(0x50BE185D),
            keyPressedColor = Color(0x70E11D48),
            textColor = Color(0xFFFFF1F2),
            textSecondaryColor = Color(0xFFFDA4AF),
            accentColor = Color(0xFFFB7185),
            keyBorderColor = Color(0x44F43F5E),
            backgroundGradient = listOf(Color(0xFF2D112C), Color(0xFF5A1846), Color(0xFF900C3F), Color(0xFFC70039)),
            keyAlpha = 0.85f,
            backdropType = "sunset"
        )

        val AURORA = KeyboardTheme(
            id = "aurora",
            name = "Northern Aurora",
            isDark = true,
            primaryColor = Color(0xFF14B8A6),
            backgroundColor = Color(0xFF041C1A),
            surfaceColor = Color(0xFF082F2C),
            keyColor = Color(0x330D9488),
            keySpecialColor = Color(0x550F766E),
            keyPressedColor = Color(0x77115E59),
            textColor = Color(0xFFF0FDFA),
            textSecondaryColor = Color(0xFF99F6E4),
            accentColor = Color(0xFF2DD4BF),
            keyBorderColor = Color(0x4414B8A6),
            backgroundGradient = listOf(Color(0xFF021B1A), Color(0xFF064E3B), Color(0xFF0F766E), Color(0xFF115E59)),
            keyAlpha = 0.85f,
            backdropType = "aurora"
        )

        val CYBERPUNK = KeyboardTheme(
            id = "cyberpunk",
            name = "Cyberpunk 2077",
            isDark = true,
            primaryColor = Color(0xFFFFEE00),
            backgroundColor = Color(0xFF05050A),
            surfaceColor = Color(0xFF0F0F1A),
            keyColor = Color(0xFF181829),
            keySpecialColor = Color(0xFF26263D),
            keyPressedColor = Color(0xFFFFEE00),
            textColor = Color(0xFF00FFFF),
            textSecondaryColor = Color(0xFFFF007F),
            accentColor = Color(0xFFFFEE00),
            keyBorderColor = Color(0x6600FFFF),
            backgroundGradient = listOf(Color(0xFF0B0014), Color(0xFF1D002C), Color(0xFF080D21)),
            keyAlpha = 0.9f,
            backdropType = "cyberpunk"
        )

        val EMERALD = KeyboardTheme(
            id = "emerald",
            name = "Emerald Neon",
            isDark = true,
            primaryColor = Color(0xFF10B981),
            backgroundColor = Color(0xFF061A14),
            surfaceColor = Color(0xFF0D2820),
            keyColor = Color(0xFF133B2F),
            keySpecialColor = Color(0xFF1D5242),
            keyPressedColor = Color(0xFF266854),
            textColor = Color(0xFFECFDF5),
            textSecondaryColor = Color(0xFF6EE7B7),
            accentColor = Color(0xFF34D399),
            keyBorderColor = Color(0x33059669),
            backdropType = "solid"
        )

        val OCEAN = KeyboardTheme(
            id = "ocean",
            name = "Deep Ocean",
            isDark = true,
            primaryColor = Color(0xFF0284C7),
            backgroundColor = Color(0xFF081426),
            surfaceColor = Color(0xFF0F243E),
            keyColor = Color(0xFF16375C),
            keySpecialColor = Color(0xFF1E4878),
            keyPressedColor = Color(0xFF275C96),
            textColor = Color(0xFFF0F9FF),
            textSecondaryColor = Color(0xFF7DD3FC),
            accentColor = Color(0xFF38BDF8),
            keyBorderColor = Color(0x330284C7),
            backdropType = "solid"
        )

        val PURPLE = KeyboardTheme(
            id = "purple",
            name = "Cyber Violet",
            isDark = true,
            primaryColor = Color(0xFF9333EA),
            backgroundColor = Color(0xFF130826),
            surfaceColor = Color(0xFF220F42),
            keyColor = Color(0xFF341763),
            keySpecialColor = Color(0xFF4A238A),
            keyPressedColor = Color(0xFF6232B3),
            textColor = Color(0xFFFAF5FF),
            textSecondaryColor = Color(0xFFD8B4FE),
            accentColor = Color(0xFFC084FC),
            keyBorderColor = Color(0x339333EA),
            backdropType = "solid"
        )

        val SAKURA = KeyboardTheme(
            id = "sakura",
            name = "Sakura Blossom",
            isDark = false,
            primaryColor = Color(0xFFE11D48),
            backgroundColor = Color(0xFFFFF1F2),
            surfaceColor = Color(0xFFFFE4E6),
            keyColor = Color(0xFFFFFFFF),
            keySpecialColor = Color(0xFFFECDD3),
            keyPressedColor = Color(0xFFFDA4AF),
            textColor = Color(0xFF881337),
            textSecondaryColor = Color(0xFF9F1239),
            accentColor = Color(0xFFF43F5E),
            keyBorderColor = Color(0x33FB7185),
            backgroundGradient = listOf(Color(0xFFFFF0F5), Color(0xFFFFDEE9), Color(0xFFB5FFFC)),
            keyAlpha = 0.92f,
            backdropType = "sakura"
        )

        val CARBON_GOLD = KeyboardTheme(
            id = "carbon_gold",
            name = "Carbon Luxury Gold",
            isDark = true,
            primaryColor = Color(0xFFEAB308),
            backgroundColor = Color(0xFF121212),
            surfaceColor = Color(0xFF1E1E1E),
            keyColor = Color(0xFF282828),
            keySpecialColor = Color(0xFF333333),
            keyPressedColor = Color(0xFF444444),
            textColor = Color(0xFFFEF08A),
            textSecondaryColor = Color(0xFFCA8A04),
            accentColor = Color(0xFFFACC15),
            keyBorderColor = Color(0x44EAB308),
            backdropType = "solid",
            isPro = true
        )

        val MINIMAL_LIGHT = KeyboardTheme(
            id = "minimal_light",
            name = "Minimal Light",
            isDark = false,
            primaryColor = Color(0xFF4F46E5),
            backgroundColor = Color(0xFFF8FAFC),
            surfaceColor = Color(0xFFFFFFFF),
            keyColor = Color(0xFFFFFFFF),
            keySpecialColor = Color(0xFFE2E8F0),
            keyPressedColor = Color(0xFFCBD5E1),
            textColor = Color(0xFF0F172A),
            textSecondaryColor = Color(0xFF64748B),
            accentColor = Color(0xFF4F46E5),
            keyBorderColor = Color(0x22CBD5E1),
            backdropType = "solid"
        )

        val AMOLED = KeyboardTheme(
            id = "amoled",
            name = "Pure AMOLED",
            isDark = true,
            primaryColor = Color(0xFF38BDF8),
            backgroundColor = Color(0xFF000000),
            surfaceColor = Color(0xFF0A0A0A),
            keyColor = Color(0xFF171717),
            keySpecialColor = Color(0xFF262626),
            keyPressedColor = Color(0xFF404040),
            textColor = Color(0xFFFFFFFF),
            textSecondaryColor = Color(0xFFA3A3A3),
            accentColor = Color(0xFF22D3EE),
            keyBorderColor = Color(0x3338BDF8),
            backdropType = "solid",
            isPro = true
        )

        val GLASSMORPHISM = KeyboardTheme(
            id = "glassmorphism",
            name = "Frosted Glassmorphism",
            isDark = true,
            primaryColor = Color(0xFF38BDF8),
            backgroundColor = Color(0xFF0B0F19),
            surfaceColor = Color(0xFF161E31),
            keyColor = Color(0x35FFFFFF),
            keySpecialColor = Color(0x48FFFFFF),
            keyPressedColor = Color(0x8038BDF8),
            textColor = Color(0xFFFFFFFF),
            textSecondaryColor = Color(0xCCBAE6FD),
            accentColor = Color(0xFF38BDF8),
            keyBorderColor = Color(0x70FFFFFF),
            backgroundGradient = listOf(Color(0xFF090D1A), Color(0xFF1E1B4B), Color(0xFF162544), Color(0xFF0F172A)),
            keyAlpha = 0.85f,
            backdropType = "glassmorphism",
            themeStyle = ThemeStyle.GLASSMORPHISM,
            keyCornerRadius = 8f,
            keyElevation = 0f,
            category = "UI Trends",
            isPro = true
        )

        val NEUMORPHISM_LIGHT = KeyboardTheme(
            id = "neumorphism_light",
            name = "Soft Neumorphism Light",
            isDark = false,
            primaryColor = Color(0xFF3B82F6),
            backgroundColor = Color(0xFFE2E8F0),
            surfaceColor = Color(0xFFE2E8F0),
            keyColor = Color(0xFFE2E8F0),
            keySpecialColor = Color(0xFFD6DFEB),
            keyPressedColor = Color(0xFFCBD5E1),
            textColor = Color(0xFF1E293B),
            textSecondaryColor = Color(0xFF64748B),
            accentColor = Color(0xFF2563EB),
            keyBorderColor = Color(0xFFCBD5E1),
            backgroundGradient = listOf(Color(0xFFE8EEF5), Color(0xFFDFE6F0)),
            keyAlpha = 1.0f,
            backdropType = "neumorphism_light",
            themeStyle = ThemeStyle.NEUMORPHISM_LIGHT,
            keyCornerRadius = 8f,
            keyElevation = 3f,
            category = "UI Trends"
        )

        val NEUMORPHISM_DARK = KeyboardTheme(
            id = "neumorphism_dark",
            name = "Soft Neumorphism Dark",
            isDark = true,
            primaryColor = Color(0xFF10B981),
            backgroundColor = Color(0xFF1E2227),
            surfaceColor = Color(0xFF1E2227),
            keyColor = Color(0xFF23282E),
            keySpecialColor = Color(0xFF2B3138),
            keyPressedColor = Color(0xFF181B1E),
            textColor = Color(0xFFF1F5F9),
            textSecondaryColor = Color(0xFF94A3B8),
            accentColor = Color(0xFF34D399),
            keyBorderColor = Color(0xFF2E343D),
            backgroundGradient = listOf(Color(0xFF23282E), Color(0xFF191C20)),
            keyAlpha = 1.0f,
            backdropType = "neumorphism_dark",
            themeStyle = ThemeStyle.NEUMORPHISM_DARK,
            keyCornerRadius = 8f,
            keyElevation = 3f,
            category = "UI Trends",
            isPro = true
        )

        val FLAT_DESIGN = KeyboardTheme(
            id = "flat_design",
            name = "Modern Flat Design",
            isDark = true,
            primaryColor = Color(0xFF2563EB),
            backgroundColor = Color(0xFF0F172A),
            surfaceColor = Color(0xFF1E293B),
            keyColor = Color(0xFF1E293B),
            keySpecialColor = Color(0xFF334155),
            keyPressedColor = Color(0xFF475569),
            textColor = Color(0xFFF8FAFC),
            textSecondaryColor = Color(0xFF94A3B8),
            accentColor = Color(0xFFF97316),
            keyBorderColor = Color(0xFF334155),
            keyAlpha = 1.0f,
            backdropType = "solid",
            themeStyle = ThemeStyle.FLAT_DESIGN,
            keyCornerRadius = 4f,
            keyElevation = 0f,
            category = "UI Trends"
        )

        val MINIMALISM = KeyboardTheme(
            id = "minimalism",
            name = "Minimalist Editorial",
            isDark = true,
            primaryColor = Color(0xFFFFFFFF),
            backgroundColor = Color(0xFF09090B),
            surfaceColor = Color(0xFF121215),
            keyColor = Color(0x18FFFFFF),
            keySpecialColor = Color(0x28FFFFFF),
            keyPressedColor = Color(0x40FFFFFF),
            textColor = Color(0xFFFAFAFA),
            textSecondaryColor = Color(0xFF71717A),
            accentColor = Color(0xFFE4E4E7),
            keyBorderColor = Color(0x1AFFFFFF),
            keyAlpha = 1.0f,
            backdropType = "solid",
            themeStyle = ThemeStyle.MINIMALISM,
            keyCornerRadius = 5f,
            keyElevation = 0f,
            category = "UI Trends"
        )

        val SKEUOMORPHISM = KeyboardTheme(
            id = "skeuomorphism",
            name = "Tactile 3D Skeuomorphic",
            isDark = true,
            primaryColor = Color(0xFF3B82F6),
            backgroundColor = Color(0xFF181A1E),
            surfaceColor = Color(0xFF22252B),
            keyColor = Color(0xFF2D323A),
            keySpecialColor = Color(0xFF383E47),
            keyPressedColor = Color(0xFF202329),
            textColor = Color(0xFFF8FAFC),
            textSecondaryColor = Color(0xFFA0ABBA),
            accentColor = Color(0xFF60A5FA),
            keyBorderColor = Color(0xFF131518),
            backgroundGradient = listOf(Color(0xFF23272E), Color(0xFF141619)),
            keyAlpha = 1.0f,
            backdropType = "skeuomorphism",
            themeStyle = ThemeStyle.SKEUOMORPHISM,
            keyCornerRadius = 6f,
            keyElevation = 4f,
            category = "UI Trends",
            isPro = true
        )

        val MATERIAL_YOU = KeyboardTheme(
            id = "material_you",
            name = "Gboard Material You",
            isDark = true,
            primaryColor = Color(0xFFA8C7FA),
            backgroundColor = Color(0xFF191C1E),
            surfaceColor = Color(0xFF222528),
            keyColor = Color(0xFF2D3135),
            keySpecialColor = Color(0xFF373B40),
            keyPressedColor = Color(0xFF45494F),
            textColor = Color(0xFFE2E2E6),
            textSecondaryColor = Color(0xFFC4C7C5),
            accentColor = Color(0xFFA8C7FA),
            keyBorderColor = Color(0x1FFFFFFF),
            keyAlpha = 1.0f,
            backdropType = "solid",
            themeStyle = ThemeStyle.MATERIAL_YOU,
            keyCornerRadius = 6f,
            keyElevation = 1.5f,
            category = "UI Trends"
        )

        // World Cup & Store Themes (Image 4)
        val SPAIN_2 = KeyboardTheme(
            id = "spain_2",
            name = "স্পেন (২) - Gold Crest",
            isDark = true,
            primaryColor = Color(0xFFF59E0B),
            backgroundColor = Color(0xFF1A0507),
            surfaceColor = Color(0xFF2E090D),
            keyColor = Color(0xFF4A0E15),
            keySpecialColor = Color(0xFF6B141E),
            keyPressedColor = Color(0xFFDC2626),
            textColor = Color(0xFFFEF3C7),
            textSecondaryColor = Color(0xFFFCD34D),
            accentColor = Color(0xFFEAB308),
            keyBorderColor = Color(0x66F59E0B),
            backgroundGradient = listOf(Color(0xFF260508), Color(0xFF4D0A11), Color(0xFF8B1220), Color(0xFF1A0507)),
            keyAlpha = 0.9f,
            backdropType = "spain_wc",
            category = "World Cup"
        )

        val SPAIN_4 = KeyboardTheme(
            id = "spain_4",
            name = "স্পেন (৪) - Trophy Glory",
            isDark = true,
            primaryColor = Color(0xFFEAB308),
            backgroundColor = Color(0xFF14080A),
            surfaceColor = Color(0xFF251014),
            keyColor = Color(0xFF38181E),
            keySpecialColor = Color(0xFF52222A),
            keyPressedColor = Color(0xFFE11D48),
            textColor = Color(0xFFFFFBEB),
            textSecondaryColor = Color(0xFFFDE68A),
            accentColor = Color(0xFFFBBF24),
            keyBorderColor = Color(0x55EAB308),
            backgroundGradient = listOf(Color(0xFF1A0B0E), Color(0xFF3B1219), Color(0xFF6E1825)),
            keyAlpha = 0.9f,
            backdropType = "spain_wc",
            category = "World Cup"
        )

        val SPAIN_3 = KeyboardTheme(
            id = "spain_3",
            name = "স্পেন (৩) - Stadium 19",
            isDark = true,
            primaryColor = Color(0xFFF97316),
            backgroundColor = Color(0xFF160B0E),
            surfaceColor = Color(0xFF2A151A),
            keyColor = Color(0xFF3E1F27),
            keySpecialColor = Color(0xFF5A2A35),
            keyPressedColor = Color(0xFFEA580C),
            textColor = Color(0xFFFFF7ED),
            textSecondaryColor = Color(0xFFFED7AA),
            accentColor = Color(0xFFFB923C),
            keyBorderColor = Color(0x55F97316),
            backgroundGradient = listOf(Color(0xFF1E0E12), Color(0xFF421B24), Color(0xFF7C2D12)),
            keyAlpha = 0.9f,
            backdropType = "spain_wc",
            category = "World Cup"
        )

        val ARGENTINA_10 = KeyboardTheme(
            id = "argentina_10",
            name = "আর্জেন্টিনা (১০) - 3 Stars",
            isDark = true,
            primaryColor = Color(0xFF38BDF8),
            backgroundColor = Color(0xFF0C1B2A),
            surfaceColor = Color(0xFF142B42),
            keyColor = Color(0xFF1C3A57),
            keySpecialColor = Color(0xFF254B70),
            keyPressedColor = Color(0xFF0284C7),
            textColor = Color(0xFFF0F9FF),
            textSecondaryColor = Color(0xFFBAE6FD),
            accentColor = Color(0xFFFACC15),
            keyBorderColor = Color(0x6638BDF8),
            backgroundGradient = listOf(Color(0xFF081420), Color(0xFF0F2E4C), Color(0xFF1E4976), Color(0xFF0A1826)),
            keyAlpha = 0.9f,
            backdropType = "argentina_wc",
            category = "World Cup",
            isPro = false
        )

        val ARGENTINA_GOLD = KeyboardTheme(
            id = "argentina_gold",
            name = "আর্জেন্টিনা (গোল্ডেন)",
            isDark = true,
            primaryColor = Color(0xFFEAB308),
            backgroundColor = Color(0xFF0B1724),
            surfaceColor = Color(0xFF142436),
            keyColor = Color(0xFF1E354D),
            keySpecialColor = Color(0xFF2A496B),
            keyPressedColor = Color(0xFFEAB308),
            textColor = Color(0xFFFEF9C3),
            textSecondaryColor = Color(0xFFFDE047),
            accentColor = Color(0xFFFACC15),
            keyBorderColor = Color(0x66EAB308),
            backgroundGradient = listOf(Color(0xFF08121C), Color(0xFF162D45), Color(0xFF3B3012)),
            keyAlpha = 0.9f,
            backdropType = "argentina_wc",
            category = "World Cup",
            isPro = true
        )

        // 10 MASTER THEMES & STYLES (MATCHING USER REFERENCE IMAGE)
        val CLASSIC_DARK = KeyboardTheme(
            id = "classic_dark",
            name = "1. Classic Dark",
            isDark = true,
            primaryColor = Color(0xFF14B8A6),
            backgroundColor = Color(0xFF0F172A),
            surfaceColor = Color(0xFF1E293B),
            keyColor = Color(0xFF1E293B),
            keySpecialColor = Color(0xFF334155),
            keyPressedColor = Color(0xFF0D9488),
            textColor = Color(0xFFF8FAFC),
            textSecondaryColor = Color(0xFF94A3B8),
            accentColor = Color(0xFF2DD4BF),
            keyBorderColor = Color(0x332DD4BF),
            backgroundGradient = listOf(Color(0xFF0B1120), Color(0xFF131D31)),
            keyAlpha = 1.0f,
            backdropType = "classic_dark",
            themeStyle = ThemeStyle.STANDARD,
            keyCornerRadius = 8f,
            keyElevation = 1.5f,
            category = "Master 10"
        )

        val GRADIENT_GLOW = KeyboardTheme(
            id = "gradient_glow",
            name = "4. Gradient Glow",
            isDark = true,
            primaryColor = Color(0xFFA855F7),
            backgroundColor = Color(0xFF0D0628),
            surfaceColor = Color(0xFF1A0B3B),
            keyColor = Color(0x387C3AED),
            keySpecialColor = Color(0x559333EA),
            keyPressedColor = Color(0x88A855F7),
            textColor = Color(0xFFFAF5FF),
            textSecondaryColor = Color(0xFFE9D5FF),
            accentColor = Color(0xFF00FFFF),
            keyBorderColor = Color(0x66C084FC),
            backgroundGradient = listOf(Color(0xFF0A0017), Color(0xFF1C053A), Color(0xFF2D0B5E), Color(0xFF0B0D2E)),
            keyAlpha = 0.82f,
            backdropType = "gradient_glow",
            themeStyle = ThemeStyle.SEMI_TRANSPARENT,
            keyCornerRadius = 8f,
            category = "Master 10"
        )

        val CRYSTAL = KeyboardTheme(
            id = "crystal",
            name = "5. Crystal 3D",
            isDark = true,
            primaryColor = Color(0xFFF59E0B),
            backgroundColor = Color(0xFF0E131F),
            surfaceColor = Color(0xFF182033),
            keyColor = Color(0xFF232E44),
            keySpecialColor = Color(0xFF2F3D58),
            keyPressedColor = Color(0xFFD97706),
            textColor = Color(0xFFFEF3C7),
            textSecondaryColor = Color(0xFFFDE68A),
            accentColor = Color(0xFFFBBF24),
            keyBorderColor = Color(0x55F59E0B),
            backgroundGradient = listOf(Color(0xFF080D18), Color(0xFF162035), Color(0xFF1F2D48)),
            keyAlpha = 1.0f,
            backdropType = "crystal",
            themeStyle = ThemeStyle.SKEUOMORPHISM,
            keyCornerRadius = 7f,
            keyElevation = 3.5f,
            category = "Master 10"
        )

        val FOREST_GREEN = KeyboardTheme(
            id = "forest_green",
            name = "6. Forest Green",
            isDark = true,
            primaryColor = Color(0xFF10B981),
            backgroundColor = Color(0xFF061A14),
            surfaceColor = Color(0xFF0D2D23),
            keyColor = Color(0xFF133D30),
            keySpecialColor = Color(0xFF1B4E3E),
            keyPressedColor = Color(0xFF059669),
            textColor = Color(0xFFECFDF5),
            textSecondaryColor = Color(0xFFA7F3D0),
            accentColor = Color(0xFF34D399),
            keyBorderColor = Color(0x4434D399),
            backgroundGradient = listOf(Color(0xFF03140F), Color(0xFF07291F), Color(0xFF0B3A2C)),
            keyAlpha = 0.95f,
            backdropType = "forest_green",
            themeStyle = ThemeStyle.TACTILE_3D,
            keyCornerRadius = 8f,
            keyElevation = 2f,
            category = "Master 10"
        )

        val NEON_CYBER = KeyboardTheme(
            id = "neon_cyber",
            name = "7. Neon Cyber",
            isDark = true,
            primaryColor = Color(0xFFFF007F),
            backgroundColor = Color(0xFF05050C),
            surfaceColor = Color(0xFF0E0E1F),
            keyColor = Color(0xFF14142B),
            keySpecialColor = Color(0xFF221F40),
            keyPressedColor = Color(0xFFFF007F),
            textColor = Color(0xFF00FFFF),
            textSecondaryColor = Color(0xFFFF77C6),
            accentColor = Color(0xFF00FFFF),
            keyBorderColor = Color(0x6600FFFF),
            backgroundGradient = listOf(Color(0xFF060312), Color(0xFF160829), Color(0xFF090D24)),
            keyAlpha = 1.0f,
            backdropType = "neon_cyber",
            themeStyle = ThemeStyle.NEOBRUTALISM,
            keyCornerRadius = 6f,
            category = "Master 10"
        )

        val LIGHT_MINIMAL = KeyboardTheme(
            id = "light_minimal",
            name = "8. Light Minimal",
            isDark = false,
            primaryColor = Color(0xFF2563EB),
            backgroundColor = Color(0xFFF1F5F9),
            surfaceColor = Color(0xFFFFFFFF),
            keyColor = Color(0xFFFFFFFF),
            keySpecialColor = Color(0xFFE2E8F0),
            keyPressedColor = Color(0xFFCBD5E1),
            textColor = Color(0xFF0F172A),
            textSecondaryColor = Color(0xFF64748B),
            accentColor = Color(0xFF38BDF8),
            keyBorderColor = Color(0x33CBD5E1),
            backgroundGradient = listOf(Color(0xFFF8FAFC), Color(0xFFE2E8F0)),
            keyAlpha = 1.0f,
            backdropType = "light_minimal",
            themeStyle = ThemeStyle.FLAT_2_0,
            keyCornerRadius = 8f,
            keyElevation = 1.0f,
            category = "Master 10"
        )

        val AMOLED_BLACK = KeyboardTheme(
            id = "amoled_black",
            name = "9. AMOLED Black",
            isDark = true,
            primaryColor = Color(0xFF06B6D4),
            backgroundColor = Color(0xFF000000),
            surfaceColor = Color(0xFF080808),
            keyColor = Color(0xFF141414),
            keySpecialColor = Color(0xFF222222),
            keyPressedColor = Color(0xFF0891B2),
            textColor = Color(0xFFFFFFFF),
            textSecondaryColor = Color(0xFFA3A3A3),
            accentColor = Color(0xFF22D3EE),
            keyBorderColor = Color(0x3322D3EE),
            keyAlpha = 1.0f,
            backdropType = "solid",
            themeStyle = ThemeStyle.TACTILE_3D,
            keyCornerRadius = 7f,
            keyElevation = 1.5f,
            category = "Master 10"
        )

        val SUNSET_AURORA = KeyboardTheme(
            id = "sunset_aurora",
            name = "10. Sunset Aurora (Translucent)",
            isDark = true,
            primaryColor = Color(0xFFF97316),
            backgroundColor = Color(0xFF250918),
            surfaceColor = Color(0xFF3D1127),
            keyColor = Color(0x35FB923C),
            keySpecialColor = Color(0x55E11D48),
            keyPressedColor = Color(0x88F97316),
            textColor = Color(0xFFFFF7ED),
            textSecondaryColor = Color(0xFFFDBA74),
            accentColor = Color(0xFFFBBF24),
            keyBorderColor = Color(0x55F97316),
            backgroundGradient = listOf(Color(0xFF200717), Color(0xFF56112C), Color(0xFF9E2335), Color(0xFFD9480F), Color(0xFFE8590C)),
            keyAlpha = 0.78f,
            backdropType = "sunset_aurora",
            themeStyle = ThemeStyle.SEMI_TRANSPARENT,
            keyCornerRadius = 8f,
            category = "Master 10"
        )

        val TACTILE_3D_DARK = KeyboardTheme(
            id = "tactile_3d_dark",
            name = "3D Mechanical Tactile",
            isDark = true,
            primaryColor = Color(0xFF6366F1),
            backgroundColor = Color(0xFF13151A),
            surfaceColor = Color(0xFF1C1F26),
            keyColor = Color(0xFF262A34),
            keySpecialColor = Color(0xFF333845),
            keyPressedColor = Color(0xFF191B21),
            textColor = Color(0xFFF8FAFC),
            textSecondaryColor = Color(0xFF94A3B8),
            accentColor = Color(0xFF818CF8),
            keyBorderColor = Color(0xFF383E4C),
            backgroundGradient = listOf(Color(0xFF161920), Color(0xFF101217)),
            keyAlpha = 1.0f,
            backdropType = "tactile_3d",
            themeStyle = ThemeStyle.TACTILE_3D,
            keyCornerRadius = 7f,
            keyElevation = 3.5f,
            category = "UI Trends"
        )

        val CLAYMORPHISM_PASTEL = KeyboardTheme(
            id = "claymorphism_pastel",
            name = "Claymorphism 3D Pastel",
            isDark = false,
            primaryColor = Color(0xFF6366F1),
            backgroundColor = Color(0xFFEEF2FF),
            surfaceColor = Color(0xFFE0E7FF),
            keyColor = Color(0xFFFFFFFF),
            keySpecialColor = Color(0xFFE0E7FF),
            keyPressedColor = Color(0xFFC7D2FE),
            textColor = Color(0xFF312E81),
            textSecondaryColor = Color(0xFF6366F1),
            accentColor = Color(0xFF4F46E5),
            keyBorderColor = Color(0xFFC7D2FE),
            backgroundGradient = listOf(Color(0xFFF5F7FF), Color(0xFFE0E7FF)),
            keyAlpha = 1.0f,
            backdropType = "claymorphism",
            themeStyle = ThemeStyle.CLAYMORPHISM,
            keyCornerRadius = 11f,
            keyElevation = 4f,
            category = "UI Trends"
        )

        val FLAT_2_0 = KeyboardTheme(
            id = "flat_2_0",
            name = "Modern Flat 2.0",
            isDark = true,
            primaryColor = Color(0xFF0EA5E9),
            backgroundColor = Color(0xFF0B132B),
            surfaceColor = Color(0xFF1C2541),
            keyColor = Color(0xFF1C2541),
            keySpecialColor = Color(0xFF3A506B),
            keyPressedColor = Color(0xFF0EA5E9),
            textColor = Color(0xFFF0FDF4),
            textSecondaryColor = Color(0xFF94A3B8),
            accentColor = Color(0xFF38BDF8),
            keyBorderColor = Color(0x3338BDF8),
            backgroundGradient = listOf(Color(0xFF0B132B), Color(0xFF1C2541)),
            keyAlpha = 1.0f,
            backdropType = "flat_2_0",
            themeStyle = ThemeStyle.FLAT_2_0,
            keyCornerRadius = 6f,
            keyElevation = 1.0f,
            category = "UI Trends"
        )

        val NEOBRUTALISM_POP = KeyboardTheme(
            id = "neobrutalism_pop",
            name = "Neobrutalism Pop Art",
            isDark = false,
            primaryColor = Color(0xFFFFE600),
            backgroundColor = Color(0xFFFFFBEB),
            surfaceColor = Color(0xFFFEF3C7),
            keyColor = Color(0xFFFFFFFF),
            keySpecialColor = Color(0xFFFFEE55),
            keyPressedColor = Color(0xFFFFD600),
            textColor = Color(0xFF000000),
            textSecondaryColor = Color(0xFF262626),
            accentColor = Color(0xFFFF5252),
            keyBorderColor = Color(0xFF000000),
            keyAlpha = 1.0f,
            backdropType = "neobrutalism",
            themeStyle = ThemeStyle.NEOBRUTALISM,
            keyCornerRadius = 5f,
            keyElevation = 0f,
            category = "UI Trends"
        )

        val SEMI_TRANSPARENT_CLASSIC = KeyboardTheme(
            id = "semi_transparent_classic",
            name = "Translucent Glass (Classic)",
            isDark = true,
            primaryColor = Color(0xFF818CF8),
            backgroundColor = Color(0xFF0F0C20),
            surfaceColor = Color(0xFF181533),
            keyColor = Color(0x33FFFFFF),
            keySpecialColor = Color(0x44818CF8),
            keyPressedColor = Color(0x776366F1),
            textColor = Color(0xFFFFFFFF),
            textSecondaryColor = Color(0xCCFFFFFF),
            accentColor = Color(0xFF818CF8),
            keyBorderColor = Color(0x40FFFFFF),
            backgroundGradient = listOf(Color(0xFF0F0C20), Color(0xFF2E1065), Color(0xFF1E1B4B)),
            keyAlpha = 0.80f,
            backdropType = "cosmic",
            themeStyle = ThemeStyle.SEMI_TRANSPARENT,
            keyCornerRadius = 8f,
            category = "Master 10"
        )

        val ALL_THEMES = listOf(
            CLASSIC_DARK,
            NEUMORPHISM_LIGHT,
            GLASSMORPHISM,
            GRADIENT_GLOW,
            CRYSTAL,
            FOREST_GREEN,
            NEON_CYBER,
            LIGHT_MINIMAL,
            AMOLED_BLACK,
            SUNSET_AURORA,
            TACTILE_3D_DARK,
            CLAYMORPHISM_PASTEL,
            FLAT_2_0,
            NEOBRUTALISM_POP,
            SEMI_TRANSPARENT_CLASSIC,
            NEUMORPHISM_DARK,
            FLAT_DESIGN,
            MINIMALISM,
            SKEUOMORPHISM,
            MATERIAL_YOU,
            SPAIN_2,
            SPAIN_4,
            SPAIN_3,
            ARGENTINA_10,
            ARGENTINA_GOLD,
            MIDNIGHT,
            COSMIC,
            SUNSET,
            AURORA,
            CYBERPUNK,
            SAKURA,
            CARBON_GOLD,
            EMERALD,
            OCEAN,
            PURPLE,
            MINIMAL_LIGHT,
            AMOLED
        )

        fun getById(id: String): KeyboardTheme {
            return ALL_THEMES.firstOrNull { it.id.equals(id, ignoreCase = true) } ?: MIDNIGHT
        }
    }
}
