package com.example.auth

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.util.Log
import com.example.data.LingoKeyPreferences
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

/**
 * Data model representing an authenticated Google Account profile.
 */
data class GoogleUser(
    val id: String,
    val email: String,
    val displayName: String,
    val photoUrl: String = "",
    val isVerified: Boolean = true,
    val cloudCredits: Int = 0
)

sealed class GoogleAuthResult {
    data class Success(val user: GoogleUser, val isNewUser: Boolean = false) : GoogleAuthResult()
    data class Error(val message: String) : GoogleAuthResult()
    object Cancelled : GoogleAuthResult()
}

/**
 * Production Google Sign-In with Firebase Authentication
 * powered by Google Play Services Auth (`GoogleSignInClient`) and Firebase Auth.
 * Opens the native Google Account Chooser dialog listing all device Google accounts.
 */
class GoogleAccountManager private constructor(
    private val context: Context,
    private val preferences: LingoKeyPreferences
) {
    private val firebaseAuth: FirebaseAuth = FirebaseAuth.getInstance()

    companion object {
        private const val TAG = "GoogleAccountManager"

        @Volatile
        private var instance: GoogleAccountManager? = null

        fun getInstance(context: Context, preferences: LingoKeyPreferences): GoogleAccountManager {
            return instance ?: synchronized(this) {
                instance ?: GoogleAccountManager(context.applicationContext, preferences).also {
                    instance = it
                }
            }
        }
    }

    /**
     * Attempts to resolve the Web Client ID generated by Google Services plugin
     * from google-services.json (R.string.default_web_client_id).
     */
    fun getWebClientId(): String? {
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        if (resId != 0) {
            val resClientId = context.getString(resId)
            if (resClientId.isNotBlank()) {
                return resClientId
            }
        }
        return null
    }

    /**
     * Builds and returns the official GoogleSignInClient.
     * Always requests Email and Profile so the native Google Account Picker
     * pops up immediately showing all accounts on the device.
     */
    fun getGoogleSignInClient(activity: Activity): GoogleSignInClient {
        val gsoBuilder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
            .requestProfile()

        // If an OAuth Web Client ID is configured in google-services.json, request ID token for Firebase Auth
        val webClientId = getWebClientId()
        if (!webClientId.isNullOrBlank()) {
            gsoBuilder.requestIdToken(webClientId)
        }

        return GoogleSignIn.getClient(activity, gsoBuilder.build())
    }

    /**
     * Checks if a Firebase or Google user is already signed in.
     */
    fun getCurrentUser(): FirebaseUser? = firebaseAuth.currentUser

    /**
     * Processes the result returned from the native Google Account Chooser intent.
     */
    suspend fun handleSignInResult(data: Intent?): GoogleAuthResult = withContext(Dispatchers.IO) {
        try {
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            val account: GoogleSignInAccount = task.getResult(ApiException::class.java)

            val id = account.id ?: ("google_" + Math.abs((account.email ?: "").hashCode()))
            val email = account.email ?: "user@gmail.com"
            val displayName = account.displayName
                ?: email.substringBefore("@").replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
            val photoUrl = account.photoUrl?.toString() ?: ""
            val idToken = account.idToken

            // If idToken is present, link with Firebase Auth
            var firebaseUser: FirebaseUser? = null
            if (!idToken.isNullOrBlank()) {
                try {
                    val credential = GoogleAuthProvider.getCredential(idToken, null)
                    val authResult = firebaseAuth.signInWithCredential(credential).awaitResult()
                    firebaseUser = authResult.user
                } catch (e: Exception) {
                    Log.w(TAG, "Firebase signInWithCredential notice: ${e.message}. Using verified Google Account profile.")
                }
            }

            val finalUid = firebaseUser?.uid ?: id
            val finalEmail = firebaseUser?.email ?: email
            val finalName = firebaseUser?.displayName ?: displayName
            val finalPhoto = firebaseUser?.photoUrl?.toString() ?: photoUrl

            val isBonusAwarded = withContext(Dispatchers.Main) {
                preferences.saveGoogleAccount(
                    id = finalUid,
                    email = finalEmail,
                    displayName = finalName,
                    photoUrl = finalPhoto
                )
            }

            val user = GoogleUser(
                id = finalUid,
                email = finalEmail,
                displayName = finalName,
                photoUrl = finalPhoto,
                isVerified = true,
                cloudCredits = preferences.aiCredits.value
            )

            GoogleAuthResult.Success(user, isNewUser = isBonusAwarded)
        } catch (e: ApiException) {
            Log.e(TAG, "Google Sign-In failed with status code: ${e.statusCode}", e)
            when (e.statusCode) {
                12501, 12502 -> GoogleAuthResult.Cancelled
                4, 8 -> GoogleAuthResult.Error("Network error. Please check your internet connection and try again.")
                else -> GoogleAuthResult.Error("Google Sign-In error (code ${e.statusCode}). Please ensure your device has Google Play Services enabled.")
            }
        } catch (e: Exception) {
            Log.e(TAG, "Sign in exception: ${e.message}", e)
            GoogleAuthResult.Error(e.message ?: "Google Sign-In could not be completed.")
        }
    }

    /**
     * Signs out the user from both Google Client and Firebase Auth.
     */
    suspend fun signOut(activity: Activity? = null) = withContext(Dispatchers.Main) {
        if (activity != null) {
            try {
                val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN).build()
                val client = GoogleSignIn.getClient(activity, gso)
                client.signOut()
            } catch (e: Exception) {
                Log.w(TAG, "Error signing out of GoogleSignInClient: ${e.message}")
            }
        }
        try {
            firebaseAuth.signOut()
        } catch (e: Exception) {
            Log.w(TAG, "Error signing out of Firebase: ${e.message}")
        }
        preferences.signOutGoogle()
    }

    /**
     * Helper extension to await Firebase Tasks with coroutines cancellation support.
     */
    private suspend fun <T> com.google.android.gms.tasks.Task<T>.awaitResult(): T =
        suspendCancellableCoroutine { cont ->
            addOnSuccessListener { cont.resume(it) }
            addOnFailureListener { cont.resumeWithException(it) }
        }
}
